### ISSUE TITLE
emacs error on startup "Symbol's value as variable is void: org-recent-headings-candidate-number-limit"

### ISSUE THREAD

**Issue by zeltak** [alphapapa/org-recent-headings#6] opened 2017-05-23 11:17 UTC
Hi

i suddenly get this error on startup:

```
Warning (initialization): An error occurred while loading ‘/home/zeltak/.emacs.d/init.el’:

Symbol's value as variable is void: org-recent-headings-candidate-number-limit

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

any clue what may cause this?

thx!

Z

**Comment by alphapapa** [comment] 2017-06-01 17:21
Hi Z,

Sorry about this, another mistake caused by my updating a package but not restarting Emacs for several days and therefore not noticing that it broke Emacs init.  I just noticed this myself when it happened to me.  I often check my GitHub participating notifications page, but that doesn't show new bugs filed against my repos.  sigh

Anyway, I'm about to push a fix for this.  The problem was that I had it set to autoload the `(with-eval-after-load 'helm`, and adding that variable to the Helm source caused it to fail because it was trying to access that variable when Helm itself was loaded, before `org-recent-headings`, so the variable wasn't defined yet.

I've changed the `(with-eval-after-load 'helm` to `(when (fboundp 'helm)`, which fixes this, and I'm making the same change for the Ivy support.  It does mean that, if you load Helm or Ivy after loading `org-recent-headings`, you'll have to `(require 'org-recent-headings)` again to load the Helm/Ivy support, but most users will probably load Helm/Ivy first.  The only other solution that I know of (but I may be missing something) would be to split Helm/Ivy support into separate packages, but the resulting packages would be so small that I don't think it would be worth it.

Thanks for reporting, as always.

**Closed** 2017-06-01 17:26 UTC
